### ISSUE TITLE
Not working with PHP 8.5

### ISSUE THREAD

**Issue by garak** [10gen-labs/mongo-php-driver-prototype#1869]
I couldn't find any explicit information about the possible compatibility of this driver with PHP 8.5, but in theory the composer declaration allows it. 

So I tried to run Docker image 8.5.0beta1-alpine with mongodb 2.1.1, but it fails. The following is a past of the last part of the output (the full output being very very lenghty):

>In file included from /tmp/pear/temp/mongodb/src/phongo_bson.c:24:
/tmp/pear/temp/mongodb/src/contrib/php_array_api.h: In function 'php_array_zval_to_string':
/tmp/pear/temp/mongodb/src/contrib/php_array_api.h:353:36: error: implicit declaration of function 'IS_INTERNED'; did you mean 'IS_STR_INTERNED'? [-Wimplicit-function-declaration]
  353 |                         *pfree = ! IS_INTERNED(Z_STR(c));
      |                                    ^~~~~~~~~~~
      |                                    IS_STR_INTERNED
make: *** [Makefile:1068: src/phongo_bson.lo] Error 1

The following Dockerfile can be used to reproduce the problem: https://github.com/dustin10/VichUploaderBundle/blob/master/docker/Dockerfile85

The file uses 8.5.0beta1-alpine, but trying with the latest available version (8.5.0beta3-alpine) leads to the same error.

**Comment by alcaeus** [comment]
2.1 is not compatible with PHP 8.5. The issue in question was fixed in #1849 and will be part of the 2.2 release. In the meantime, you can [install the extension from source](https://www.php.net/manual/en/mongodb.installation.php#mongodb.installation.manual) on PHP 8.5.

**Comment by garak** [comment]
Is the missing compatibility restricted to this, or are there other blockers?
If the case is the former, what about backporting the fix to the 2.1 branch?

**Comment by jmikola** [comment]
PHP 8.5 has yet to settle on a final API version (e.g. https://github.com/php/php-src/commit/7225a11e59598ab01dc2a195b4ca6ba2db028538), which usually comes with the release candidates. We can consider backporting a compatibility update to `v2.1` when preparing our 2.2.0 release, but it'd be premature to do so before PHP 8.5's API version is locked in.

**Comment by alcaeus** [comment]
Version 2.1.2 with support for PHP 8.5 has been released.
