### ISSUE TITLE
Release 2.3.2 breaks pecl install in docker (zstd.h not found)

### ISSUE THREAD

**Issue by tux-rampage** [10gen-labs/mongo-php-driver-prototype#2020]
### Bug Report

Since release 2.3.2 the pecl install/build fails in docker environments complaining about a missing `zstd.h` header while version 2.3.1 builds and installs without any issues.

### Environment

- Docker (Image `docker.io/library/php:8.4-cli`)
- Debian GNU/Linux 13
- PHP 8.4.21 (cli) (built: May 19 2026 23:08:19) (NTS)
- MongoDB 2.3.2 (pecl)

### Test Script

```bash
pecl install mongodb
```

### Expected and Actual Behavior

**Expected:** Build and install the mongodb extension
**Actual:** Build failure

### Debug Log

Truncated to the last relevant lines:

```
/tmp/pear/temp/mongodb/src/libmongoc/src/libmongoc/src/mongoc/mongoc-compression.c:34:10: fatal error: zstd.h: No such file or directory
   34 | #include <zstd.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:502: src/libmongoc/src/libmongoc/src/mongoc/mongoc-compression.lo] Error 1
ERROR: `make' failed
```

**Comment by alcaeus** [comment]
I'm currently debugging the source of the problem. There seems to be an issue with recent changes regarding out-of-source builds and `pecl` not liking them. On systems where installing via `pecl` failed, I was able to successfully install it using [PIE](https://github.com/php/pie), so if that's an option this would be a good opportunity to move away from `pecl` and provide relief while we work on fixing the issue. Instructions on how to use `pie` within docker can be found in [PIE's usage docs](https://github.com/php/pie/blob/1.5.x/docs/usage.md#docker-installation).

**Comment by a8ns** [comment]
Confirmed on **Alpine 3.23 / musl / `php:8.4.16-fpm-alpine3.23`** — same root cause, different symptom.

## Environment

- Base image: `php:8.4.16-fpm-alpine3.23` (`sha256:56aed89b8fd022516b400526db7d4b699fd437372c585cd5785de9634bb7cdd7`)
- GCC: 15.2.0-r2 (Alpine)
- linux-headers: 6.16.12-r0

## Symptom

```
mongoc-client.c:461:7: error: implicit declaration of function 'res_ninit'; did you mean 'res_init'?
mongoc-client.c:465:14: error: implicit declaration of function 'res_nsearch'; did you mean 'res_search'?
mongoc-client.c:539:4: error: implicit declaration of function 'res_nclose'
make: *** [Makefile:466: src/libmongoc/src/libmongoc/src/mongoc/mongoc-client.lo] Error 1
```

## Root cause

The `configure` run correctly detects `res_nsearch: no` / `res_search: yes` on musl and `config.status` **does** regenerate `mongoc-config.h` with `MONGOC_HAVE_RES_NSEARCH=0`. However, the compiler never sees that file — it picks up the pre-bundled `mongoc-config.h` from the source tree instead, which was generated on a glibc system with `MONGOC_HAVE_RES_NSEARCH=1` hardcoded.

The regression is in commit 5d19cfa (PHPC-2647/PHPC-2715). In 2.3.1, `config.m4` used `PHP_ADD_INCLUDE` with an explicit absolute path to the build directory:

```m4
PHP_ADD_INCLUDE([$abs_builddir/$php_mongodb_ext_builddir/src/libmongoc/src/libmongoc/src])
```

In 2.3.2 these were replaced with `PHP_MONGODB_ADD_BUILD_INCLUDE`, which resolves the build dir via `PHP_EXPAND_PATH(PHP_EXT_BUILDDIR(mongodb), ...)`. In a standard PECL/phpize build the resolved path does not point to where `config.status` actually writes the generated headers, so the compiler falls back to the source-tree copy.

## Proposed fix for the package

The `PHP_MONGODB_ADD_BUILD_INCLUDE` macro could fall back to `$abs_builddir` explicitly for phpize builds (where `PHP_EXT_BUILDDIR` expands to `.`), or the `AC_CONFIG_FILES` paths and include paths could be verified to match in a phpize + musl CI job. A minimal targeted fix would be to restore the `PHP_ADD_INCLUDE($abs_builddir/...)` lines alongside the new macro.

## Workaround

Pin to 2.3.1:

```dockerfile
RUN pecl install mongodb-2.3.1
```

**Comment by GromNaN** [comment]
Thanks for reporting this issue. The fix will be released tomorrow in 2.3.3
